config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'
  post '/log/create', to: 'log#create'
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user
  validates :date_played, :user_id, :opponent_id, :your_score, :their_score, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def history
  end

  def log
    @log = Log.new
  end
end

app/controllers/log_controller.rb
class LogController < ApplicationController

  def create
    @log = Log.new(log_params)
    logger.debug "New log: #{@log.attributes.inspect}"
    if @log.save
      redirect_to :controller => 'home', :action => 'history', flash: {message: "Log created successfully"}
    else 
      redirect_to log_url(@log)
    end
  end

  private

  def log_params
    params.require(:log).permit(:user_id, :opponent_id, :date_played, :your_score, :their_score)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/log_helper.rb
module LogHelper
end

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<p id="alert alert-success" role="alert"><%= flash[:message] %></p>

<table class="table">
  <tr>
    <th>Date</th>
    <th>Opponent</th>
    <th>Score</th>
    <th>Result</th>
  </tr>
 
  <% Log.where('user_id = ?', current_user.id).order(date_played: :desc).each do |log| %>
    <tr>
      <td><%= log.date_played.strftime("%b %e, %Y") %></td>
      <td><%= User.find(log.opponent_id).email %></td>
      <td><%= log.your_score.to_s + '-' + log.their_score.to_s%> </td>
      <% if log.your_score > log.their_score %>
        <td>W</td>
      <% elsif log.your_score < log.their_score %>
        <td>L</td>
      <% else %>
        <td>T</td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<p id="alert alert-success" role="alert"><%= flash[:message] %></p>

<table class="table">
  <tr>
    <th>Rank</th>
    <th>Name</th>
    <th>Score</th>
    <th>Games Played</th>
  </tr>
 
  <% Log.select("user_id as user_id, sum(your_score) as score, count(id) as games ").group("user_id").order("score").each_with_index do |log, index| %>
    <tr>
      <td># <%= index + 1 %></td>
      <td><%= User.find(log.user_id).email %></td>
      <td><%= log.score %></td>
      <td><%= log.games %></td>
    </tr>
  <% end %>
</table>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="panel panel-default">
  <div class="panel-body">
  <%= form_for :log, url: log_create_url do |f| %>
    
    <% if @log.errors.any? %>
      <div style="padding-top: 0px" class="alert alert-danger" id="error_explanation">
        <h3>
          <%= pluralize(@log.errors.count, "error") %> prohibited
          this log from being saved:
        </h3>
        <ul>
          <% @log.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id, :value => current_user.id %>
    <p>
      <%= f.label :date_played %><br>
      <%= f.date_select :date_played, :include_blank => true, :order => [:day, :month, :year], class: 'form-control' %>
    </p>
   
    <p>
      <%= f.label :opponent_id %><br>
      <%= f.collection_select(:opponent_id, User.where('id NOT IN (?)', current_user.id), :id, :email) %>
    </p>

    <p>
      <%= f.label :your_score %><br>
      <%= f.number_field :your_score, min: 0 %>
    </p>

    <p>
      <%= f.label :their_score %><br>
      <%= f.number_field :their_score, min: 0 %>
    </p>
   
    <p>
      <%= f.submit 'Save', :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', history_path, :class => 'btn btn-default' %>
    </p>
  <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', '/log', class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="/history">History</a></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>